### ISSUE TITLE
MultiShiftActionForm location rendered as "title"

### ISSUE THREAD

**Issue by joe-irving** [zetkin/zetkin-common#60]
When displaying events in a campaign, the location is sometimes being shown as just "title" not the location name despite it being returned in the API reponse:

# Expected Behaviour

All events listed on campaign pages like this: https://www.zetk.in/o/633/campaigns/1868 have a location listed that matches the location of the event:

![Screenshot from 2023-07-11 14-14-16](https://github.com/zetkin/zetkin-common/assets/71458765/68bdc3a7-b3be-44fa-bd58-6631ca6524b2)

# Actual Behaviour

"title" appears next to the location, seemingly only for multi shift events

![Screenshot from 2023-07-11 14-00-03](https://github.com/zetkin/zetkin-common/assets/71458765/0657dd57-0ef8-41e0-9709-f6dbf22b57b8)

# Possible solution

It looks like in line 94 of  `./campaignForm/action/MultiShiftActionForm.jsx` there need to be some `[]` s added to make it:

```js
let location = actions[0].getIn(['location', 'title']);
```

**Comment by richardolsson** [comment]
Great report! Will fix this as part of next release (mid-August).
